# Generated by Django 5.2.16 on 2026-09-11 13:16

import wagtailvideos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0015_video_height_video_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=wagtailvideos.models.get_upload_to, verbose_name='thumbnail'),
        ),
    ]
